### ISSUE TITLE
Strange offset when exporting the ifc with ifc manager

### ISSUE THREAD

**Issue by simondilhas** [BIM-Tools/SketchUp-IFC-Manager#70] opened 2024-11-07 10:42 UTC
I modeled this in SketchUp:

![image](https://github.com/user-attachments/assets/5249a7ac-2ca3-438c-9f55-058a33fbc603)

when exporting with the ifc manager, the upper building storeys are not aligned anymore:

![image](https://github.com/user-attachments/assets/c637c8c4-6d2f-4bf3-a324-8e49a4b33420)

when using the standard Sketchup exporter everything is fine.

![image](https://github.com/user-attachments/assets/e8461175-be77-4b4c-8cfa-dc6f4c43385b)
[Mustermodell (test SimpleBIM).zip](https://github.com/user-attachments/files/17660193/Mustermodell.test.SimpleBIM.zip)

I included the original Sketchup file and the IFC files aswell.

The issue must be in the Building Storey. I exploded the stories and recreated and everything works again. 
Just thought I make you aware of it...

**Comment by jbrouwerdigibase** [comment] 2024-11-09 21:21
Thanks! Using the 5.3.0 version?

**Comment by jbrouwerdigibase** [comment] 2024-11-09 21:26
I can't reproduce it, I think you accidentally shared the model with exploded buildingstoreys, do you still have the original?

**Comment by janbrouwer** [comment] 2024-12-28 16:17
Should be fixed in [release v5.4.0](https://github.com/BIM-Tools/SketchUp-IFC-Manager/releases/tag/v5.4.0)

**Closed by janbrouwer** 2024-12-28 16:17 UTC
